version: 2

jobs:
  # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys

      # CircleCI に登録した環境変数を使って SSH
      - run: ssh ${USER_NAME}@${HOST_NAME} "cd /var/wwww/mrg-web-site && git pull origin main"

workflows:
  version: 2
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
  deploy:
    # build ジョブと deploy ジョブを登録する
    jobs:
      - deploy:
          filters:
            branches:
              only: main
